/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareerElementUpdate
 */
export interface CareerElementUpdate {
    /**
     * The position or degree name (e.g. ‐Software Engineer‐ or ‐B.Sc. in Economics‐).
     * @type {string}
     * @memberof CareerElementUpdate
     */
    title?: string;
    /**
     * Start date (e.g. matriculation date or job start).
     * @type {Date}
     * @memberof CareerElementUpdate
     */
    fromDate?: Date | null;
    /**
     * End date (e.g. graduation date or job end); if omitted, it’s ongoing.
     * @type {Date}
     * @memberof CareerElementUpdate
     */
    untilDate?: Date | null;
    /**
     * Free‐form description of responsibilities or achievements.
     * @type {string}
     * @memberof CareerElementUpdate
     */
    description?: string | null;
    /**
     * Name of the institution or company.
     * @type {string}
     * @memberof CareerElementUpdate
     */
    organizationName?: string | null;
    /**
     * Final grade or GPA (e.g. ‐3.7/4.0‐ or ‐First‐class honors‐).
     * @type {string}
     * @memberof CareerElementUpdate
     */
    finalGrade?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CareerElementUpdate
     */
    degree?: string;
    /**
     * 
     * @type {string}
     * @memberof CareerElementUpdate
     */
    position?: string;
}

/**
 * Check if a given object implements the CareerElementUpdate interface.
 */
export function instanceOfCareerElementUpdate(value: object): value is CareerElementUpdate {
    return true;
}

export function CareerElementUpdateFromJSON(json: any): CareerElementUpdate {
    return CareerElementUpdateFromJSONTyped(json, false);
}

export function CareerElementUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerElementUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'fromDate': json['fromDate'] == null ? undefined : (new Date(json['fromDate'])),
        'untilDate': json['untilDate'] == null ? undefined : (new Date(json['untilDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'organizationName': json['organizationName'] == null ? undefined : json['organizationName'],
        'finalGrade': json['finalGrade'] == null ? undefined : json['finalGrade'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function CareerElementUpdateToJSON(json: any): CareerElementUpdate {
    return CareerElementUpdateToJSONTyped(json, false);
}

export function CareerElementUpdateToJSONTyped(value?: CareerElementUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'fromDate': value['fromDate'] == null ? undefined : ((value['fromDate'] as any).toISOString().substring(0,10)),
        'untilDate': value['untilDate'] == null ? undefined : ((value['untilDate'] as any).toISOString().substring(0,10)),
        'description': value['description'],
        'organizationName': value['organizationName'],
        'finalGrade': value['finalGrade'],
        'degree': value['degree'],
        'position': value['position'],
    };
}

