/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareerElement
 */
export interface CareerElement {
    /**
     * Unique ID of this career element (education or job).
     * @type {string}
     * @memberof CareerElement
     */
    id: string;
    /**
     * The type of career element (education or job).
     * @type {string}
     * @memberof CareerElement
     */
    kind: CareerElementKindEnum;
    /**
     * The position or degree name (e.g. ‐Software Engineer‐ or ‐B.Sc. in Economics‐).
     * @type {string}
     * @memberof CareerElement
     */
    title: string;
    /**
     * Start date (e.g. matriculation date or job start).
     * @type {Date}
     * @memberof CareerElement
     */
    fromDate: Date | null;
    /**
     * End date (e.g. graduation date or job end); if omitted, it’s ongoing.
     * @type {Date}
     * @memberof CareerElement
     */
    untilDate?: Date | null;
    /**
     * Free‐form description of responsibilities or achievements.
     * @type {string}
     * @memberof CareerElement
     */
    description?: string | null;
    /**
     * Name of the institution or company.
     * @type {string}
     * @memberof CareerElement
     */
    organizationName?: string | null;
    /**
     * Final grade or GPA (e.g. ‐3.7/4.0‐ or ‐First‐class honors‐).
     * @type {string}
     * @memberof CareerElement
     */
    finalGrade?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CareerElement
     */
    degree?: string;
    /**
     * 
     * @type {string}
     * @memberof CareerElement
     */
    position?: string;
}


/**
 * @export
 */
export const CareerElementKindEnum = {
    Education: 'education',
    Job: 'job'
} as const;
export type CareerElementKindEnum = typeof CareerElementKindEnum[keyof typeof CareerElementKindEnum];


/**
 * Check if a given object implements the CareerElement interface.
 */
export function instanceOfCareerElement(value: object): value is CareerElement {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('fromDate' in value) || value['fromDate'] === undefined) return false;
    return true;
}

export function CareerElementFromJSON(json: any): CareerElement {
    return CareerElementFromJSONTyped(json, false);
}

export function CareerElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerElement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'kind': json['kind'],
        'title': json['title'],
        'fromDate': (json['fromDate'] == null ? null : new Date(json['fromDate'])),
        'untilDate': json['untilDate'] == null ? undefined : (new Date(json['untilDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'organizationName': json['organizationName'] == null ? undefined : json['organizationName'],
        'finalGrade': json['finalGrade'] == null ? undefined : json['finalGrade'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function CareerElementToJSON(json: any): CareerElement {
    return CareerElementToJSONTyped(json, false);
}

export function CareerElementToJSONTyped(value?: CareerElement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'kind': value['kind'],
        'title': value['title'],
        'fromDate': (value['fromDate'] == null ? null : (value['fromDate'] as any).toISOString().substring(0,10)),
        'untilDate': value['untilDate'] == null ? undefined : ((value['untilDate'] as any).toISOString().substring(0,10)),
        'description': value['description'],
        'organizationName': value['organizationName'],
        'finalGrade': value['finalGrade'],
        'degree': value['degree'],
        'position': value['position'],
    };
}

