/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPublicSummary } from './UserPublicSummary';
import {
    UserPublicSummaryFromJSON,
    UserPublicSummaryFromJSONTyped,
    UserPublicSummaryToJSON,
    UserPublicSummaryToJSONTyped,
} from './UserPublicSummary';
import type { JobPosting } from './JobPosting';
import {
    JobPostingFromJSON,
    JobPostingFromJSONTyped,
    JobPostingToJSON,
    JobPostingToJSONTyped,
} from './JobPosting';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';
import type { Cooperation } from './Cooperation';
import {
    CooperationFromJSON,
    CooperationFromJSONTyped,
    CooperationToJSON,
    CooperationToJSONTyped,
} from './Cooperation';

/**
 * 
 * @export
 * @interface Conversation
 */
export interface Conversation {
    /**
     * Unique identifier for this conversation.
     * @type {string}
     * @memberof Conversation
     */
    id: string;
    /**
     * When the conversation was created.
     * @type {Date}
     * @memberof Conversation
     */
    createdAt: Date;
    /**
     * Unique identifier for the participating retiree.
     * @type {Array<UserPublicSummary>}
     * @memberof Conversation
     */
    participants: Array<UserPublicSummary>;
    /**
     * 
     * @type {Array<Message>}
     * @memberof Conversation
     */
    messages: Array<Message>;
    /**
     * 
     * @type {JobPosting}
     * @memberof Conversation
     */
    jobPosting?: JobPosting;
    /**
     * 
     * @type {Cooperation}
     * @memberof Conversation
     */
    cooperation?: Cooperation;
}

/**
 * Check if a given object implements the Conversation interface.
 */
export function instanceOfConversation(value: object): value is Conversation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ConversationFromJSON(json: any): Conversation {
    return ConversationFromJSONTyped(json, false);
}

export function ConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conversation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'createdAt': (new Date(json['createdAt'])),
        'participants': ((json['participants'] as Array<any>).map(UserPublicSummaryFromJSON)),
        'messages': ((json['messages'] as Array<any>).map(MessageFromJSON)),
        'jobPosting': json['jobPosting'] == null ? undefined : JobPostingFromJSON(json['jobPosting']),
        'cooperation': json['cooperation'] == null ? undefined : CooperationFromJSON(json['cooperation']),
    };
}

export function ConversationToJSON(json: any): Conversation {
    return ConversationToJSONTyped(json, false);
}

export function ConversationToJSONTyped(value?: Conversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'participants': ((value['participants'] as Array<any>).map(UserPublicSummaryToJSON)),
        'messages': ((value['messages'] as Array<any>).map(MessageToJSON)),
        'jobPosting': JobPostingToJSON(value['jobPosting']),
        'cooperation': CooperationToJSON(value['cooperation']),
    };
}

