/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cooperation
 */
export interface Cooperation {
    /**
     * 
     * @type {string}
     * @memberof Cooperation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Cooperation
     */
    retireeId: string;
    /**
     * 
     * @type {string}
     * @memberof Cooperation
     */
    jobPostingId: string;
    /**
     * 
     * @type {string}
     * @memberof Cooperation
     */
    status: CooperationStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Cooperation
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CooperationStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Declined: 'declined'
} as const;
export type CooperationStatusEnum = typeof CooperationStatusEnum[keyof typeof CooperationStatusEnum];


/**
 * Check if a given object implements the Cooperation interface.
 */
export function instanceOfCooperation(value: object): value is Cooperation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('retireeId' in value) || value['retireeId'] === undefined) return false;
    if (!('jobPostingId' in value) || value['jobPostingId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CooperationFromJSON(json: any): Cooperation {
    return CooperationFromJSONTyped(json, false);
}

export function CooperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cooperation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'retireeId': json['retireeId'],
        'jobPostingId': json['jobPostingId'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CooperationToJSON(json: any): Cooperation {
    return CooperationToJSONTyped(json, false);
}

export function CooperationToJSONTyped(value?: Cooperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'retireeId': value['retireeId'],
        'jobPostingId': value['jobPostingId'],
        'status': value['status'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

