/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeferredResponse
 */
export interface DeferredResponse {
    /**
     * ‐Your request was accepted, but no new run will start right now.‐
     * 
     * @type {string}
     * @memberof DeferredResponse
     */
    message?: string;
    /**
     * If known, when the matching run will actually run; otherwise null.
     * 
     * @type {Date}
     * @memberof DeferredResponse
     */
    scheduledAt?: Date | null;
}

/**
 * Check if a given object implements the DeferredResponse interface.
 */
export function instanceOfDeferredResponse(value: object): value is DeferredResponse {
    return true;
}

export function DeferredResponseFromJSON(json: any): DeferredResponse {
    return DeferredResponseFromJSONTyped(json, false);
}

export function DeferredResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeferredResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'scheduledAt': json['scheduledAt'] == null ? undefined : (new Date(json['scheduledAt'])),
    };
}

export function DeferredResponseToJSON(json: any): DeferredResponse {
    return DeferredResponseToJSONTyped(json, false);
}

export function DeferredResponseToJSONTyped(value?: DeferredResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'scheduledAt': value['scheduledAt'] == null ? undefined : ((value['scheduledAt'] as any).toISOString()),
    };
}

