/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Degree
 */
export interface Degree {
    /**
     * Internal UUID for this degree (e.g. BSc, MSc, etc.).
     * @type {string}
     * @memberof Degree
     */
    id: string;
    /**
     * The name of the degree (e.g. ‐Bachelor of Science‐).
     * @type {string}
     * @memberof Degree
     */
    title: string;
}

/**
 * Check if a given object implements the Degree interface.
 */
export function instanceOfDegree(value: object): value is Degree {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DegreeFromJSON(json: any): Degree {
    return DegreeFromJSONTyped(json, false);
}

export function DegreeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Degree {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'title': json['title'],
    };
}

export function DegreeToJSON(json: any): Degree {
    return DegreeToJSONTyped(json, false);
}

export function DegreeToJSONTyped(value?: Degree | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'title': value['title'],
    };
}

