/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpertiseArea
 */
export interface ExpertiseArea {
    /**
     * UUID for this expertise area (e.g. ‐Data Science‐).
     * @type {string}
     * @memberof ExpertiseArea
     */
    id: string;
    /**
     * Human‐readable name of the expertise area.
     * @type {string}
     * @memberof ExpertiseArea
     */
    name: string;
}

/**
 * Check if a given object implements the ExpertiseArea interface.
 */
export function instanceOfExpertiseArea(value: object): value is ExpertiseArea {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExpertiseAreaFromJSON(json: any): ExpertiseArea {
    return ExpertiseAreaFromJSONTyped(json, false);
}

export function ExpertiseAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpertiseArea {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'name': json['name'],
    };
}

export function ExpertiseAreaToJSON(json: any): ExpertiseArea {
    return ExpertiseAreaToJSONTyped(json, false);
}

export function ExpertiseAreaToJSONTyped(value?: ExpertiseArea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'name': value['name'],
    };
}

