/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FundingStatus
 */
export interface FundingStatus {
    /**
     * Unique identifier for this funding status.
     * @type {string}
     * @memberof FundingStatus
     */
    id: string;
    /**
     * Human‐readable name of the funding status (e.g. ‐Seed‐, ‐Series A‐).
     * @type {string}
     * @memberof FundingStatus
     */
    title: string;
}

/**
 * Check if a given object implements the FundingStatus interface.
 */
export function instanceOfFundingStatus(value: object): value is FundingStatus {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function FundingStatusFromJSON(json: any): FundingStatus {
    return FundingStatusFromJSONTyped(json, false);
}

export function FundingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FundingStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'title': json['title'],
    };
}

export function FundingStatusToJSON(json: any): FundingStatus {
    return FundingStatusToJSONTyped(json, false);
}

export function FundingStatusToJSONTyped(value?: FundingStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'title': value['title'],
    };
}

