/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageProficiency } from './LanguageProficiency';
import {
    LanguageProficiencyFromJSON,
    LanguageProficiencyFromJSONTyped,
    LanguageProficiencyToJSON,
    LanguageProficiencyToJSONTyped,
} from './LanguageProficiency';

/**
 * 
 * @export
 * @interface JobPostingCreate
 */
export interface JobPostingCreate {
    /**
     * 
     * @type {string}
     * @memberof JobPostingCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostingCreate
     */
    startupId: string;
    /**
     * 
     * @type {string}
     * @memberof JobPostingCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobPostingCreate
     */
    requiredZip?: string | null;
    /**
     * City where the job must be performed.
     * @type {string}
     * @memberof JobPostingCreate
     */
    requiredCity?: string | null;
    /**
     * Country where job must be performed.
     * @type {string}
     * @memberof JobPostingCreate
     */
    requiredCountry?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobPostingCreate
     */
    approxDurationWeeks?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobPostingCreate
     */
    approxHoursPerWeek?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobPostingCreate
     */
    approxDaysPerWeek?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobPostingCreate
     */
    approxHourlySalaryEUR?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof JobPostingCreate
     */
    desiredStartDate?: Date | null;
    /**
     * 
     * @type {Array<LanguageProficiency>}
     * @memberof JobPostingCreate
     */
    matchingLanguageProficiencies?: Array<LanguageProficiency>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobPostingCreate
     */
    matchingExpertiseAreas?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobPostingCreate
     */
    matchingSkills?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobPostingCreate
     */
    matchingPositions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobPostingCreate
     */
    matchingDegrees?: Array<string>;
}

/**
 * Check if a given object implements the JobPostingCreate interface.
 */
export function instanceOfJobPostingCreate(value: object): value is JobPostingCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startupId' in value) || value['startupId'] === undefined) return false;
    return true;
}

export function JobPostingCreateFromJSON(json: any): JobPostingCreate {
    return JobPostingCreateFromJSONTyped(json, false);
}

export function JobPostingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPostingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'startupId': json['startupId'],
        'description': json['description'] == null ? undefined : json['description'],
        'requiredZip': json['requiredZip'] == null ? undefined : json['requiredZip'],
        'requiredCity': json['requiredCity'] == null ? undefined : json['requiredCity'],
        'requiredCountry': json['requiredCountry'] == null ? undefined : json['requiredCountry'],
        'approxDurationWeeks': json['approxDurationWeeks'] == null ? undefined : json['approxDurationWeeks'],
        'approxHoursPerWeek': json['approxHoursPerWeek'] == null ? undefined : json['approxHoursPerWeek'],
        'approxDaysPerWeek': json['approxDaysPerWeek'] == null ? undefined : json['approxDaysPerWeek'],
        'approxHourlySalaryEUR': json['approxHourlySalaryEUR'] == null ? undefined : json['approxHourlySalaryEUR'],
        'desiredStartDate': json['desiredStartDate'] == null ? undefined : (new Date(json['desiredStartDate'])),
        'matchingLanguageProficiencies': json['matchingLanguageProficiencies'] == null ? undefined : ((json['matchingLanguageProficiencies'] as Array<any>).map(LanguageProficiencyFromJSON)),
        'matchingExpertiseAreas': json['matchingExpertiseAreas'] == null ? undefined : json['matchingExpertiseAreas'],
        'matchingSkills': json['matchingSkills'] == null ? undefined : json['matchingSkills'],
        'matchingPositions': json['matchingPositions'] == null ? undefined : json['matchingPositions'],
        'matchingDegrees': json['matchingDegrees'] == null ? undefined : json['matchingDegrees'],
    };
}

export function JobPostingCreateToJSON(json: any): JobPostingCreate {
    return JobPostingCreateToJSONTyped(json, false);
}

export function JobPostingCreateToJSONTyped(value?: JobPostingCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'startupId': value['startupId'],
        'description': value['description'],
        'requiredZip': value['requiredZip'],
        'requiredCity': value['requiredCity'],
        'requiredCountry': value['requiredCountry'],
        'approxDurationWeeks': value['approxDurationWeeks'],
        'approxHoursPerWeek': value['approxHoursPerWeek'],
        'approxDaysPerWeek': value['approxDaysPerWeek'],
        'approxHourlySalaryEUR': value['approxHourlySalaryEUR'],
        'desiredStartDate': value['desiredStartDate'] == null ? undefined : ((value['desiredStartDate'] as any).toISOString().substring(0,10)),
        'matchingLanguageProficiencies': value['matchingLanguageProficiencies'] == null ? undefined : ((value['matchingLanguageProficiencies'] as Array<any>).map(LanguageProficiencyToJSON)),
        'matchingExpertiseAreas': value['matchingExpertiseAreas'],
        'matchingSkills': value['matchingSkills'],
        'matchingPositions': value['matchingPositions'],
        'matchingDegrees': value['matchingDegrees'],
    };
}

