/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LanguageProficiencyLevel
 */
export interface LanguageProficiencyLevel {
    /**
     * Unique identifier for this proficiency level.
     * @type {string}
     * @memberof LanguageProficiencyLevel
     */
    id: string;
    /**
     * CEFR code (A1…C2)
     * @type {string}
     * @memberof LanguageProficiencyLevel
     */
    code: string;
}

/**
 * Check if a given object implements the LanguageProficiencyLevel interface.
 */
export function instanceOfLanguageProficiencyLevel(value: object): value is LanguageProficiencyLevel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function LanguageProficiencyLevelFromJSON(json: any): LanguageProficiencyLevel {
    return LanguageProficiencyLevelFromJSONTyped(json, false);
}

export function LanguageProficiencyLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageProficiencyLevel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'code': json['code'],
    };
}

export function LanguageProficiencyLevelToJSON(json: any): LanguageProficiencyLevel {
    return LanguageProficiencyLevelToJSONTyped(json, false);
}

export function LanguageProficiencyLevelToJSONTyped(value?: LanguageProficiencyLevel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'code': value['code'],
    };
}

