/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutPost200Response
 */
export interface LogoutPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof LogoutPost200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the LogoutPost200Response interface.
 */
export function instanceOfLogoutPost200Response(value: object): value is LogoutPost200Response {
    return true;
}

export function LogoutPost200ResponseFromJSON(json: any): LogoutPost200Response {
    return LogoutPost200ResponseFromJSONTyped(json, false);
}

export function LogoutPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function LogoutPost200ResponseToJSON(json: any): LogoutPost200Response {
    return LogoutPost200ResponseToJSONTyped(json, false);
}

export function LogoutPost200ResponseToJSONTyped(value?: LogoutPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

