/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchingRunRequest
 */
export interface MatchingRunRequest {
    /**
     * UUID of the job posting to match against.
     * @type {string}
     * @memberof MatchingRunRequest
     */
    jobPostingId?: string;
}

/**
 * Check if a given object implements the MatchingRunRequest interface.
 */
export function instanceOfMatchingRunRequest(value: object): value is MatchingRunRequest {
    return true;
}

export function MatchingRunRequestFromJSON(json: any): MatchingRunRequest {
    return MatchingRunRequestFromJSONTyped(json, false);
}

export function MatchingRunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchingRunRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jobPostingId': json['jobPostingId'] == null ? undefined : json['jobPostingId'],
    };
}

export function MatchingRunRequestToJSON(json: any): MatchingRunRequest {
    return MatchingRunRequestToJSONTyped(json, false);
}

export function MatchingRunRequestToJSONTyped(value?: MatchingRunRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobPostingId': value['jobPostingId'],
    };
}

