/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchingRun
 */
export interface MatchingRun {
    /**
     * UUID of the newly created matching run.
     * @type {string}
     * @memberof MatchingRun
     */
    id: string;
    /**
     * When this matching run was actually started.
     * @type {Date}
     * @memberof MatchingRun
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the MatchingRun interface.
 */
export function instanceOfMatchingRun(value: object): value is MatchingRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MatchingRunFromJSON(json: any): MatchingRun {
    return MatchingRunFromJSONTyped(json, false);
}

export function MatchingRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchingRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function MatchingRunToJSON(json: any): MatchingRun {
    return MatchingRunToJSONTyped(json, false);
}

export function MatchingRunToJSONTyped(value?: MatchingRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

