/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationActionsInner
 */
export interface NotificationActionsInner {
    /**
     * 
     * @type {string}
     * @memberof NotificationActionsInner
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationActionsInner
     */
    url: string;
}

/**
 * Check if a given object implements the NotificationActionsInner interface.
 */
export function instanceOfNotificationActionsInner(value: object): value is NotificationActionsInner {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function NotificationActionsInnerFromJSON(json: any): NotificationActionsInner {
    return NotificationActionsInnerFromJSONTyped(json, false);
}

export function NotificationActionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationActionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'url': json['url'],
    };
}

export function NotificationActionsInnerToJSON(json: any): NotificationActionsInner {
    return NotificationActionsInnerToJSONTyped(json, false);
}

export function NotificationActionsInnerToJSONTyped(value?: NotificationActionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'url': value['url'],
    };
}

