/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageProficiency } from './LanguageProficiency';
import {
    LanguageProficiencyFromJSON,
    LanguageProficiencyFromJSONTyped,
    LanguageProficiencyToJSON,
    LanguageProficiencyToJSONTyped,
} from './LanguageProficiency';
import type { CareerElement } from './CareerElement';
import {
    CareerElementFromJSON,
    CareerElementFromJSONTyped,
    CareerElementToJSON,
    CareerElementToJSONTyped,
} from './CareerElement';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface RetireeUpdate
 */
export interface RetireeUpdate {
    /**
     * Unique identifier for any user (retiree or startup).
     * @type {string}
     * @memberof RetireeUpdate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RetireeUpdate
     */
    userType?: RetireeUpdateUserTypeEnum;
    /**
     * Must be unique; used for magic‐link login.
     * @type {string}
     * @memberof RetireeUpdate
     */
    email: string;
    /**
     * (Optional) Stored hash if you ever add password auth. For now, not used.
     * @type {string}
     * @memberof RetireeUpdate
     */
    passwordHash?: string | null;
    /**
     * Last name of the retiree/startup user.
     * @type {string}
     * @memberof RetireeUpdate
     */
    nameLast: string;
    /**
     * First name of the retiree/startup user.
     * @type {string}
     * @memberof RetireeUpdate
     */
    nameFirst: string;
    /**
     * 
     * @type {string}
     * @memberof RetireeUpdate
     */
    profilePicture?: string | null;
    /**
     * Date and time when the user was created.
     * @type {Date}
     * @memberof RetireeUpdate
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<Notification>}
     * @memberof RetireeUpdate
     */
    notifications?: Array<Notification>;
    /**
     * A short bio or ‐About me‐ text.
     * @type {string}
     * @memberof RetireeUpdate
     */
    aboutMe?: string | null;
    /**
     * Date of birth.
     * @type {Date}
     * @memberof RetireeUpdate
     */
    birthday?: Date | null;
    /**
     * Date when the retiree first retired.
     * @type {Date}
     * @memberof RetireeUpdate
     */
    retiredSince?: Date | null;
    /**
     * Desired hourly salary in EUR.
     * @type {number}
     * @memberof RetireeUpdate
     */
    expectedHourlySalaryEUR?: number | null;
    /**
     * Desired number of work hours per week.
     * @type {number}
     * @memberof RetireeUpdate
     */
    desiredWorkHoursPerWeek?: number | null;
    /**
     * Street address.
     * @type {string}
     * @memberof RetireeUpdate
     */
    addressStreet?: string | null;
    /**
     * ZIP/postal code.
     * @type {string}
     * @memberof RetireeUpdate
     */
    addressZip?: string | null;
    /**
     * City.
     * @type {string}
     * @memberof RetireeUpdate
     */
    addressCity?: string | null;
    /**
     * Country.
     * @type {string}
     * @memberof RetireeUpdate
     */
    addressCountry?: string | null;
    /**
     * True if the retiree has finished the onboarding tutorial.
     * @type {boolean}
     * @memberof RetireeUpdate
     */
    hasCompletedTutorial?: boolean;
    /**
     * Current status the retiree on the platform.
     * @type {string}
     * @memberof RetireeUpdate
     */
    status?: RetireeUpdateStatusEnum;
    /**
     * List of skills (max 10).
     * @type {Array<string>}
     * @memberof RetireeUpdate
     */
    skills?: Array<string>;
    /**
     * List of expertise areas (max 5).
     * @type {Array<string>}
     * @memberof RetireeUpdate
     */
    expertiseAreas?: Array<string>;
    /**
     * List of language proficiencies.
     * @type {Array<LanguageProficiency>}
     * @memberof RetireeUpdate
     */
    languageProficiencies?: Array<LanguageProficiency>;
    /**
     * List of career elements (education and job history).
     * @type {Array<CareerElement>}
     * @memberof RetireeUpdate
     */
    careerElements?: Array<CareerElement>;
}


/**
 * @export
 */
export const RetireeUpdateUserTypeEnum = {
    Retiree: 'Retiree',
    Startup: 'Startup'
} as const;
export type RetireeUpdateUserTypeEnum = typeof RetireeUpdateUserTypeEnum[keyof typeof RetireeUpdateUserTypeEnum];

/**
 * @export
 */
export const RetireeUpdateStatusEnum = {
    Available: 'available',
    Atcapacity: 'atcapacity'
} as const;
export type RetireeUpdateStatusEnum = typeof RetireeUpdateStatusEnum[keyof typeof RetireeUpdateStatusEnum];


/**
 * Check if a given object implements the RetireeUpdate interface.
 */
export function instanceOfRetireeUpdate(value: object): value is RetireeUpdate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('nameLast' in value) || value['nameLast'] === undefined) return false;
    if (!('nameFirst' in value) || value['nameFirst'] === undefined) return false;
    return true;
}

export function RetireeUpdateFromJSON(json: any): RetireeUpdate {
    return RetireeUpdateFromJSONTyped(json, false);
}

export function RetireeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetireeUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'userType': json['userType'] == null ? undefined : json['userType'],
        'email': json['email'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'nameLast': json['nameLast'],
        'nameFirst': json['nameFirst'],
        'profilePicture': json['profilePicture'] == null ? undefined : json['profilePicture'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'aboutMe': json['aboutMe'] == null ? undefined : json['aboutMe'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'retiredSince': json['retiredSince'] == null ? undefined : (new Date(json['retiredSince'])),
        'expectedHourlySalaryEUR': json['expectedHourlySalaryEUR'] == null ? undefined : json['expectedHourlySalaryEUR'],
        'desiredWorkHoursPerWeek': json['desiredWorkHoursPerWeek'] == null ? undefined : json['desiredWorkHoursPerWeek'],
        'addressStreet': json['addressStreet'] == null ? undefined : json['addressStreet'],
        'addressZip': json['addressZip'] == null ? undefined : json['addressZip'],
        'addressCity': json['addressCity'] == null ? undefined : json['addressCity'],
        'addressCountry': json['addressCountry'] == null ? undefined : json['addressCountry'],
        'hasCompletedTutorial': json['hasCompletedTutorial'] == null ? undefined : json['hasCompletedTutorial'],
        'status': json['status'] == null ? undefined : json['status'],
        'skills': json['skills'] == null ? undefined : json['skills'],
        'expertiseAreas': json['expertiseAreas'] == null ? undefined : json['expertiseAreas'],
        'languageProficiencies': json['languageProficiencies'] == null ? undefined : ((json['languageProficiencies'] as Array<any>).map(LanguageProficiencyFromJSON)),
        'careerElements': json['careerElements'] == null ? undefined : ((json['careerElements'] as Array<any>).map(CareerElementFromJSON)),
    };
}

export function RetireeUpdateToJSON(json: any): RetireeUpdate {
    return RetireeUpdateToJSONTyped(json, false);
}

export function RetireeUpdateToJSONTyped(value?: RetireeUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'userType': value['userType'],
        'email': value['email'],
        'passwordHash': value['passwordHash'],
        'nameLast': value['nameLast'],
        'nameFirst': value['nameFirst'],
        'profilePicture': value['profilePicture'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'notifications': value['notifications'] == null ? undefined : ((value['notifications'] as Array<any>).map(NotificationToJSON)),
        'aboutMe': value['aboutMe'],
        'birthday': value['birthday'] == null ? undefined : ((value['birthday'] as any).toISOString().substring(0,10)),
        'retiredSince': value['retiredSince'] == null ? undefined : ((value['retiredSince'] as any).toISOString().substring(0,10)),
        'expectedHourlySalaryEUR': value['expectedHourlySalaryEUR'],
        'desiredWorkHoursPerWeek': value['desiredWorkHoursPerWeek'],
        'addressStreet': value['addressStreet'],
        'addressZip': value['addressZip'],
        'addressCity': value['addressCity'],
        'addressCountry': value['addressCountry'],
        'hasCompletedTutorial': value['hasCompletedTutorial'],
        'status': value['status'],
        'skills': value['skills'],
        'expertiseAreas': value['expertiseAreas'],
        'languageProficiencies': value['languageProficiencies'] == null ? undefined : ((value['languageProficiencies'] as Array<any>).map(LanguageProficiencyToJSON)),
        'careerElements': value['careerElements'] == null ? undefined : ((value['careerElements'] as Array<any>).map(CareerElementToJSON)),
    };
}

