/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageProficiency } from './LanguageProficiency';
import {
    LanguageProficiencyFromJSON,
    LanguageProficiencyFromJSONTyped,
    LanguageProficiencyToJSON,
    LanguageProficiencyToJSONTyped,
} from './LanguageProficiency';
import type { CareerElement } from './CareerElement';
import {
    CareerElementFromJSON,
    CareerElementFromJSONTyped,
    CareerElementToJSON,
    CareerElementToJSONTyped,
} from './CareerElement';

/**
 * 
 * @export
 * @interface RetireeCreate
 */
export interface RetireeCreate {
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    nameLast: string;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    nameFirst: string;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    profilePicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    status: RetireeCreateStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof RetireeCreate
     */
    hasCompletedTutorial: boolean;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    aboutMe?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RetireeCreate
     */
    birthday?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RetireeCreate
     */
    retiredSince?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof RetireeCreate
     */
    expectedHourlySalaryEUR?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RetireeCreate
     */
    desiredWorkHoursPerWeek?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    addressStreet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    addressZip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    addressCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RetireeCreate
     */
    addressCountry?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RetireeCreate
     */
    skills?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RetireeCreate
     */
    expertiseAreas?: Array<string>;
    /**
     * 
     * @type {Array<LanguageProficiency>}
     * @memberof RetireeCreate
     */
    languageProficiencies?: Array<LanguageProficiency>;
    /**
     * 
     * @type {Array<CareerElement>}
     * @memberof RetireeCreate
     */
    careerElements?: Array<CareerElement>;
}


/**
 * @export
 */
export const RetireeCreateStatusEnum = {
    Available: 'available',
    Atcapacity: 'atcapacity'
} as const;
export type RetireeCreateStatusEnum = typeof RetireeCreateStatusEnum[keyof typeof RetireeCreateStatusEnum];


/**
 * Check if a given object implements the RetireeCreate interface.
 */
export function instanceOfRetireeCreate(value: object): value is RetireeCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('nameLast' in value) || value['nameLast'] === undefined) return false;
    if (!('nameFirst' in value) || value['nameFirst'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('hasCompletedTutorial' in value) || value['hasCompletedTutorial'] === undefined) return false;
    return true;
}

export function RetireeCreateFromJSON(json: any): RetireeCreate {
    return RetireeCreateFromJSONTyped(json, false);
}

export function RetireeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetireeCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'nameLast': json['nameLast'],
        'nameFirst': json['nameFirst'],
        'profilePicture': json['profilePicture'] == null ? undefined : json['profilePicture'],
        'status': json['status'],
        'hasCompletedTutorial': json['hasCompletedTutorial'],
        'aboutMe': json['aboutMe'] == null ? undefined : json['aboutMe'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'retiredSince': json['retiredSince'] == null ? undefined : (new Date(json['retiredSince'])),
        'expectedHourlySalaryEUR': json['expectedHourlySalaryEUR'] == null ? undefined : json['expectedHourlySalaryEUR'],
        'desiredWorkHoursPerWeek': json['desiredWorkHoursPerWeek'] == null ? undefined : json['desiredWorkHoursPerWeek'],
        'addressStreet': json['addressStreet'] == null ? undefined : json['addressStreet'],
        'addressZip': json['addressZip'] == null ? undefined : json['addressZip'],
        'addressCity': json['addressCity'] == null ? undefined : json['addressCity'],
        'addressCountry': json['addressCountry'] == null ? undefined : json['addressCountry'],
        'skills': json['skills'] == null ? undefined : json['skills'],
        'expertiseAreas': json['expertiseAreas'] == null ? undefined : json['expertiseAreas'],
        'languageProficiencies': json['languageProficiencies'] == null ? undefined : ((json['languageProficiencies'] as Array<any>).map(LanguageProficiencyFromJSON)),
        'careerElements': json['careerElements'] == null ? undefined : ((json['careerElements'] as Array<any>).map(CareerElementFromJSON)),
    };
}

export function RetireeCreateToJSON(json: any): RetireeCreate {
    return RetireeCreateToJSONTyped(json, false);
}

export function RetireeCreateToJSONTyped(value?: RetireeCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'nameLast': value['nameLast'],
        'nameFirst': value['nameFirst'],
        'profilePicture': value['profilePicture'],
        'status': value['status'],
        'hasCompletedTutorial': value['hasCompletedTutorial'],
        'aboutMe': value['aboutMe'],
        'birthday': value['birthday'] == null ? undefined : ((value['birthday'] as any).toISOString().substring(0,10)),
        'retiredSince': value['retiredSince'] == null ? undefined : ((value['retiredSince'] as any).toISOString().substring(0,10)),
        'expectedHourlySalaryEUR': value['expectedHourlySalaryEUR'],
        'desiredWorkHoursPerWeek': value['desiredWorkHoursPerWeek'],
        'addressStreet': value['addressStreet'],
        'addressZip': value['addressZip'],
        'addressCity': value['addressCity'],
        'addressCountry': value['addressCountry'],
        'skills': value['skills'],
        'expertiseAreas': value['expertiseAreas'],
        'languageProficiencies': value['languageProficiencies'] == null ? undefined : ((value['languageProficiencies'] as Array<any>).map(LanguageProficiencyToJSON)),
        'careerElements': value['careerElements'] == null ? undefined : ((value['careerElements'] as Array<any>).map(CareerElementToJSON)),
    };
}

