/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartupCreate
 */
export interface StartupCreate {
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    aboutUs?: string;
    /**
     * Last Name of the main contact person.
     * @type {string}
     * @memberof StartupCreate
     */
    contactPersonNameLast?: string;
    /**
     * First Name of the main contact person.
     * @type {string}
     * @memberof StartupCreate
     */
    contactPersonNameFirst?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    contactPersonPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    industry?: string;
    /**
     * City.
     * @type {string}
     * @memberof StartupCreate
     */
    addressCity?: string | null;
    /**
     * Country.
     * @type {string}
     * @memberof StartupCreate
     */
    addressCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    fundingStatus?: string;
    /**
     * 
     * @type {number}
     * @memberof StartupCreate
     */
    fulltimeEmployeesNum?: number;
    /**
     * 
     * @type {number}
     * @memberof StartupCreate
     */
    foundingYear?: number;
    /**
     * 
     * @type {number}
     * @memberof StartupCreate
     */
    revenuePerYearEUR?: number;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    imprintUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    websiteUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupCreate
     */
    logoUrl?: string | null;
    /**
     * Stripe Customer ID.
     * @type {string}
     * @memberof StartupCreate
     */
    stripeCustomerId?: string | null;
    /**
     * Stripe Price ID.
     * @type {string}
     * @memberof StartupCreate
     */
    stripePriceId?: string | null;
    /**
     * When the Stripe subscription runs out.
     * @type {Date}
     * @memberof StartupCreate
     */
    stripeSubscriptionExpiryDate?: Date | null;
    /**
     * Current WiseUp subscription tier.
     * @type {string}
     * @memberof StartupCreate
     */
    wiseUpSubscriptionTier?: StartupCreateWiseUpSubscriptionTierEnum;
    /**
     * Balance of ‐connections‐/credits the startup has on a monthly basis. Gets reset every month.
     * @type {number}
     * @memberof StartupCreate
     */
    monthlyConnectionBalance?: number;
    /**
     * Balance of ‐connections‐/credits the startup has on a permanent basis. Does not reset. only available as extension to the gold tier.
     * @type {number}
     * @memberof StartupCreate
     */
    permanentConnectionBalance?: number;
    /**
     * List of job postings for this startup.
     * @type {Array<string>}
     * @memberof StartupCreate
     */
    jobPostings?: Array<string>;
}


/**
 * @export
 */
export const StartupCreateWiseUpSubscriptionTierEnum = {
    Free: 'free',
    Silver: 'silver',
    Gold: 'gold'
} as const;
export type StartupCreateWiseUpSubscriptionTierEnum = typeof StartupCreateWiseUpSubscriptionTierEnum[keyof typeof StartupCreateWiseUpSubscriptionTierEnum];


/**
 * Check if a given object implements the StartupCreate interface.
 */
export function instanceOfStartupCreate(value: object): value is StartupCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function StartupCreateFromJSON(json: any): StartupCreate {
    return StartupCreateFromJSONTyped(json, false);
}

export function StartupCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartupCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'title': json['title'],
        'aboutUs': json['aboutUs'] == null ? undefined : json['aboutUs'],
        'contactPersonNameLast': json['contactPersonNameLast'] == null ? undefined : json['contactPersonNameLast'],
        'contactPersonNameFirst': json['contactPersonNameFirst'] == null ? undefined : json['contactPersonNameFirst'],
        'contactPersonPicture': json['contactPersonPicture'] == null ? undefined : json['contactPersonPicture'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'addressCity': json['addressCity'] == null ? undefined : json['addressCity'],
        'addressCountry': json['addressCountry'] == null ? undefined : json['addressCountry'],
        'fundingStatus': json['fundingStatus'] == null ? undefined : json['fundingStatus'],
        'fulltimeEmployeesNum': json['fulltimeEmployeesNum'] == null ? undefined : json['fulltimeEmployeesNum'],
        'foundingYear': json['foundingYear'] == null ? undefined : json['foundingYear'],
        'revenuePerYearEUR': json['revenuePerYearEUR'] == null ? undefined : json['revenuePerYearEUR'],
        'imprintUrl': json['imprintUrl'] == null ? undefined : json['imprintUrl'],
        'websiteUrl': json['websiteUrl'] == null ? undefined : json['websiteUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'stripeCustomerId': json['stripeCustomerId'] == null ? undefined : json['stripeCustomerId'],
        'stripePriceId': json['stripePriceId'] == null ? undefined : json['stripePriceId'],
        'stripeSubscriptionExpiryDate': json['stripeSubscriptionExpiryDate'] == null ? undefined : (new Date(json['stripeSubscriptionExpiryDate'])),
        'wiseUpSubscriptionTier': json['wiseUpSubscriptionTier'] == null ? undefined : json['wiseUpSubscriptionTier'],
        'monthlyConnectionBalance': json['monthlyConnectionBalance'] == null ? undefined : json['monthlyConnectionBalance'],
        'permanentConnectionBalance': json['permanentConnectionBalance'] == null ? undefined : json['permanentConnectionBalance'],
        'jobPostings': json['jobPostings'] == null ? undefined : json['jobPostings'],
    };
}

export function StartupCreateToJSON(json: any): StartupCreate {
    return StartupCreateToJSONTyped(json, false);
}

export function StartupCreateToJSONTyped(value?: StartupCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'title': value['title'],
        'aboutUs': value['aboutUs'],
        'contactPersonNameLast': value['contactPersonNameLast'],
        'contactPersonNameFirst': value['contactPersonNameFirst'],
        'contactPersonPicture': value['contactPersonPicture'],
        'industry': value['industry'],
        'addressCity': value['addressCity'],
        'addressCountry': value['addressCountry'],
        'fundingStatus': value['fundingStatus'],
        'fulltimeEmployeesNum': value['fulltimeEmployeesNum'],
        'foundingYear': value['foundingYear'],
        'revenuePerYearEUR': value['revenuePerYearEUR'],
        'imprintUrl': value['imprintUrl'],
        'websiteUrl': value['websiteUrl'],
        'logoUrl': value['logoUrl'],
        'stripeCustomerId': value['stripeCustomerId'],
        'stripePriceId': value['stripePriceId'],
        'stripeSubscriptionExpiryDate': value['stripeSubscriptionExpiryDate'] == null ? undefined : ((value['stripeSubscriptionExpiryDate'] as any).toISOString().substring(0,10)),
        'wiseUpSubscriptionTier': value['wiseUpSubscriptionTier'],
        'monthlyConnectionBalance': value['monthlyConnectionBalance'],
        'permanentConnectionBalance': value['permanentConnectionBalance'],
        'jobPostings': value['jobPostings'],
    };
}

