/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface StartupUpdate
 */
export interface StartupUpdate {
    /**
     * Unique identifier for any user (retiree or startup).
     * @type {string}
     * @memberof StartupUpdate
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    userType?: StartupUpdateUserTypeEnum;
    /**
     * Must be unique; used for magic‐link login.
     * @type {string}
     * @memberof StartupUpdate
     */
    email: string;
    /**
     * (Optional) Stored hash if you ever add password auth. For now, not used.
     * @type {string}
     * @memberof StartupUpdate
     */
    passwordHash?: string | null;
    /**
     * Last name of the retiree/startup user.
     * @type {string}
     * @memberof StartupUpdate
     */
    nameLast: string;
    /**
     * First name of the retiree/startup user.
     * @type {string}
     * @memberof StartupUpdate
     */
    nameFirst: string;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    profilePicture?: string | null;
    /**
     * Date and time when the user was created.
     * @type {Date}
     * @memberof StartupUpdate
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<Notification>}
     * @memberof StartupUpdate
     */
    notifications?: Array<Notification>;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    aboutUs?: string;
    /**
     * Last Name of the main contact person.
     * @type {string}
     * @memberof StartupUpdate
     */
    contactPersonNameLast?: string;
    /**
     * First Name of the main contact person.
     * @type {string}
     * @memberof StartupUpdate
     */
    contactPersonNameFirst?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    contactPersonPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    industry?: string;
    /**
     * City.
     * @type {string}
     * @memberof StartupUpdate
     */
    addressCity?: string | null;
    /**
     * Country.
     * @type {string}
     * @memberof StartupUpdate
     */
    addressCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    fundingStatus?: string;
    /**
     * 
     * @type {number}
     * @memberof StartupUpdate
     */
    fulltimeEmployeesNum?: number;
    /**
     * 
     * @type {number}
     * @memberof StartupUpdate
     */
    foundingYear?: number;
    /**
     * 
     * @type {number}
     * @memberof StartupUpdate
     */
    revenuePerYearEUR?: number;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    imprintUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    websiteUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof StartupUpdate
     */
    logoUrl?: string | null;
    /**
     * List of job postings for this startup.
     * @type {Array<string>}
     * @memberof StartupUpdate
     */
    jobPostings?: Array<string>;
}


/**
 * @export
 */
export const StartupUpdateUserTypeEnum = {
    Retiree: 'Retiree',
    Startup: 'Startup'
} as const;
export type StartupUpdateUserTypeEnum = typeof StartupUpdateUserTypeEnum[keyof typeof StartupUpdateUserTypeEnum];


/**
 * Check if a given object implements the StartupUpdate interface.
 */
export function instanceOfStartupUpdate(value: object): value is StartupUpdate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('nameLast' in value) || value['nameLast'] === undefined) return false;
    if (!('nameFirst' in value) || value['nameFirst'] === undefined) return false;
    return true;
}

export function StartupUpdateFromJSON(json: any): StartupUpdate {
    return StartupUpdateFromJSONTyped(json, false);
}

export function StartupUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartupUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'userType': json['userType'] == null ? undefined : json['userType'],
        'email': json['email'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'nameLast': json['nameLast'],
        'nameFirst': json['nameFirst'],
        'profilePicture': json['profilePicture'] == null ? undefined : json['profilePicture'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'aboutUs': json['aboutUs'] == null ? undefined : json['aboutUs'],
        'contactPersonNameLast': json['contactPersonNameLast'] == null ? undefined : json['contactPersonNameLast'],
        'contactPersonNameFirst': json['contactPersonNameFirst'] == null ? undefined : json['contactPersonNameFirst'],
        'contactPersonPicture': json['contactPersonPicture'] == null ? undefined : json['contactPersonPicture'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'addressCity': json['addressCity'] == null ? undefined : json['addressCity'],
        'addressCountry': json['addressCountry'] == null ? undefined : json['addressCountry'],
        'fundingStatus': json['fundingStatus'] == null ? undefined : json['fundingStatus'],
        'fulltimeEmployeesNum': json['fulltimeEmployeesNum'] == null ? undefined : json['fulltimeEmployeesNum'],
        'foundingYear': json['foundingYear'] == null ? undefined : json['foundingYear'],
        'revenuePerYearEUR': json['revenuePerYearEUR'] == null ? undefined : json['revenuePerYearEUR'],
        'imprintUrl': json['imprintUrl'] == null ? undefined : json['imprintUrl'],
        'websiteUrl': json['websiteUrl'] == null ? undefined : json['websiteUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'jobPostings': json['jobPostings'] == null ? undefined : json['jobPostings'],
    };
}

export function StartupUpdateToJSON(json: any): StartupUpdate {
    return StartupUpdateToJSONTyped(json, false);
}

export function StartupUpdateToJSONTyped(value?: StartupUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'userType': value['userType'],
        'email': value['email'],
        'passwordHash': value['passwordHash'],
        'nameLast': value['nameLast'],
        'nameFirst': value['nameFirst'],
        'profilePicture': value['profilePicture'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'notifications': value['notifications'] == null ? undefined : ((value['notifications'] as Array<any>).map(NotificationToJSON)),
        'title': value['title'],
        'aboutUs': value['aboutUs'],
        'contactPersonNameLast': value['contactPersonNameLast'],
        'contactPersonNameFirst': value['contactPersonNameFirst'],
        'contactPersonPicture': value['contactPersonPicture'],
        'industry': value['industry'],
        'addressCity': value['addressCity'],
        'addressCountry': value['addressCountry'],
        'fundingStatus': value['fundingStatus'],
        'fulltimeEmployeesNum': value['fulltimeEmployeesNum'],
        'foundingYear': value['foundingYear'],
        'revenuePerYearEUR': value['revenuePerYearEUR'],
        'imprintUrl': value['imprintUrl'],
        'websiteUrl': value['websiteUrl'],
        'logoUrl': value['logoUrl'],
        'jobPostings': value['jobPostings'],
    };
}

