/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface Startup
 */
export interface Startup {
    /**
     * Unique identifier for any user (retiree or startup).
     * @type {string}
     * @memberof Startup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Startup
     */
    userType?: StartupUserTypeEnum;
    /**
     * Must be unique; used for magic‐link login.
     * @type {string}
     * @memberof Startup
     */
    email: string;
    /**
     * (Optional) Stored hash if you ever add password auth. For now, not used.
     * @type {string}
     * @memberof Startup
     */
    passwordHash?: string | null;
    /**
     * Last name of the retiree/startup user.
     * @type {string}
     * @memberof Startup
     */
    nameLast: string;
    /**
     * First name of the retiree/startup user.
     * @type {string}
     * @memberof Startup
     */
    nameFirst: string;
    /**
     * 
     * @type {string}
     * @memberof Startup
     */
    profilePicture?: string | null;
    /**
     * Date and time when the user was created.
     * @type {Date}
     * @memberof Startup
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<Notification>}
     * @memberof Startup
     */
    notifications?: Array<Notification>;
    /**
     * The official name of the startup.
     * @type {string}
     * @memberof Startup
     */
    title: string;
    /**
     * A description of the startup (‐About us‐).
     * @type {string}
     * @memberof Startup
     */
    aboutUs?: string;
    /**
     * Last Name of the main contact person.
     * @type {string}
     * @memberof Startup
     */
    contactPersonNameLast?: string;
    /**
     * First Name of the main contact person.
     * @type {string}
     * @memberof Startup
     */
    contactPersonNameFirst?: string;
    /**
     * URL to the contact person's picture.
     * @type {string}
     * @memberof Startup
     */
    contactPersonPicture?: string | null;
    /**
     * Industry or sector (e.g., ‐FinTech‐, ‐HealthTech‐).
     * @type {string}
     * @memberof Startup
     */
    industry?: string;
    /**
     * City.
     * @type {string}
     * @memberof Startup
     */
    addressCity?: string | null;
    /**
     * Country.
     * @type {string}
     * @memberof Startup
     */
    addressCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Startup
     */
    fundingStatus?: string;
    /**
     * Number of full‐time employees.
     * @type {number}
     * @memberof Startup
     */
    fulltimeEmployeesNum?: number;
    /**
     * Year the startup was founded.
     * @type {number}
     * @memberof Startup
     */
    foundingYear?: number;
    /**
     * Annual revenue in EUR.
     * @type {number}
     * @memberof Startup
     */
    revenuePerYearEUR?: number;
    /**
     * Link to the legally required imprint page (if applicable).
     * @type {string}
     * @memberof Startup
     */
    imprintUrl?: string;
    /**
     * Public website URL.
     * @type {string}
     * @memberof Startup
     */
    websiteUrl?: string;
    /**
     * URL to the startup’s logo.
     * @type {string}
     * @memberof Startup
     */
    logoUrl?: string | null;
    /**
     * Stripe Customer ID.
     * @type {string}
     * @memberof Startup
     */
    stripeCustomerId?: string | null;
    /**
     * Stripe Price ID.
     * @type {string}
     * @memberof Startup
     */
    stripePriceId?: string | null;
    /**
     * When the Stripe subscription runs out.
     * @type {Date}
     * @memberof Startup
     */
    stripeSubscriptionExpiryDate?: Date | null;
    /**
     * Current WiseUp subscription tier.
     * @type {string}
     * @memberof Startup
     */
    wiseUpSubscriptionTier?: StartupWiseUpSubscriptionTierEnum;
    /**
     * Balance of ‐connections‐/credits the startup has on a monthly basis. Gets reset every month.
     * @type {number}
     * @memberof Startup
     */
    monthlyConnectionBalance?: number;
    /**
     * Balance of ‐connections‐/credits the startup has on a permanent basis. Does not reset. only available as extension to the gold tier.
     * @type {number}
     * @memberof Startup
     */
    permanentConnectionBalance?: number;
    /**
     * List of job postings for this startup.
     * @type {Array<string>}
     * @memberof Startup
     */
    jobPostings?: Array<string>;
}


/**
 * @export
 */
export const StartupUserTypeEnum = {
    Retiree: 'Retiree',
    Startup: 'Startup'
} as const;
export type StartupUserTypeEnum = typeof StartupUserTypeEnum[keyof typeof StartupUserTypeEnum];

/**
 * @export
 */
export const StartupWiseUpSubscriptionTierEnum = {
    Free: 'free',
    Silver: 'silver',
    Gold: 'gold'
} as const;
export type StartupWiseUpSubscriptionTierEnum = typeof StartupWiseUpSubscriptionTierEnum[keyof typeof StartupWiseUpSubscriptionTierEnum];


/**
 * Check if a given object implements the Startup interface.
 */
export function instanceOfStartup(value: object): value is Startup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('nameLast' in value) || value['nameLast'] === undefined) return false;
    if (!('nameFirst' in value) || value['nameFirst'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function StartupFromJSON(json: any): Startup {
    return StartupFromJSONTyped(json, false);
}

export function StartupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Startup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'userType': json['userType'] == null ? undefined : json['userType'],
        'email': json['email'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'nameLast': json['nameLast'],
        'nameFirst': json['nameFirst'],
        'profilePicture': json['profilePicture'] == null ? undefined : json['profilePicture'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'notifications': json['notifications'] == null ? undefined : ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'title': json['title'],
        'aboutUs': json['aboutUs'] == null ? undefined : json['aboutUs'],
        'contactPersonNameLast': json['contactPersonNameLast'] == null ? undefined : json['contactPersonNameLast'],
        'contactPersonNameFirst': json['contactPersonNameFirst'] == null ? undefined : json['contactPersonNameFirst'],
        'contactPersonPicture': json['contactPersonPicture'] == null ? undefined : json['contactPersonPicture'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'addressCity': json['addressCity'] == null ? undefined : json['addressCity'],
        'addressCountry': json['addressCountry'] == null ? undefined : json['addressCountry'],
        'fundingStatus': json['fundingStatus'] == null ? undefined : json['fundingStatus'],
        'fulltimeEmployeesNum': json['fulltimeEmployeesNum'] == null ? undefined : json['fulltimeEmployeesNum'],
        'foundingYear': json['foundingYear'] == null ? undefined : json['foundingYear'],
        'revenuePerYearEUR': json['revenuePerYearEUR'] == null ? undefined : json['revenuePerYearEUR'],
        'imprintUrl': json['imprintUrl'] == null ? undefined : json['imprintUrl'],
        'websiteUrl': json['websiteUrl'] == null ? undefined : json['websiteUrl'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'stripeCustomerId': json['stripeCustomerId'] == null ? undefined : json['stripeCustomerId'],
        'stripePriceId': json['stripePriceId'] == null ? undefined : json['stripePriceId'],
        'stripeSubscriptionExpiryDate': json['stripeSubscriptionExpiryDate'] == null ? undefined : (new Date(json['stripeSubscriptionExpiryDate'])),
        'wiseUpSubscriptionTier': json['wiseUpSubscriptionTier'] == null ? undefined : json['wiseUpSubscriptionTier'],
        'monthlyConnectionBalance': json['monthlyConnectionBalance'] == null ? undefined : json['monthlyConnectionBalance'],
        'permanentConnectionBalance': json['permanentConnectionBalance'] == null ? undefined : json['permanentConnectionBalance'],
        'jobPostings': json['jobPostings'] == null ? undefined : json['jobPostings'],
    };
}

export function StartupToJSON(json: any): Startup {
    return StartupToJSONTyped(json, false);
}

export function StartupToJSONTyped(value?: Startup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'userType': value['userType'],
        'email': value['email'],
        'passwordHash': value['passwordHash'],
        'nameLast': value['nameLast'],
        'nameFirst': value['nameFirst'],
        'profilePicture': value['profilePicture'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'notifications': value['notifications'] == null ? undefined : ((value['notifications'] as Array<any>).map(NotificationToJSON)),
        'title': value['title'],
        'aboutUs': value['aboutUs'],
        'contactPersonNameLast': value['contactPersonNameLast'],
        'contactPersonNameFirst': value['contactPersonNameFirst'],
        'contactPersonPicture': value['contactPersonPicture'],
        'industry': value['industry'],
        'addressCity': value['addressCity'],
        'addressCountry': value['addressCountry'],
        'fundingStatus': value['fundingStatus'],
        'fulltimeEmployeesNum': value['fulltimeEmployeesNum'],
        'foundingYear': value['foundingYear'],
        'revenuePerYearEUR': value['revenuePerYearEUR'],
        'imprintUrl': value['imprintUrl'],
        'websiteUrl': value['websiteUrl'],
        'logoUrl': value['logoUrl'],
        'stripeCustomerId': value['stripeCustomerId'],
        'stripePriceId': value['stripePriceId'],
        'stripeSubscriptionExpiryDate': value['stripeSubscriptionExpiryDate'] == null ? undefined : ((value['stripeSubscriptionExpiryDate'] as any).toISOString().substring(0,10)),
        'wiseUpSubscriptionTier': value['wiseUpSubscriptionTier'],
        'monthlyConnectionBalance': value['monthlyConnectionBalance'],
        'permanentConnectionBalance': value['permanentConnectionBalance'],
        'jobPostings': value['jobPostings'],
    };
}

