/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadImage200Response
 */
export interface UploadImage200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UploadImage200Response
     */
    success?: boolean;
    /**
     * The URL of the uploaded image.
     * @type {string}
     * @memberof UploadImage200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the UploadImage200Response interface.
 */
export function instanceOfUploadImage200Response(value: object): value is UploadImage200Response {
    return true;
}

export function UploadImage200ResponseFromJSON(json: any): UploadImage200Response {
    return UploadImage200ResponseFromJSONTyped(json, false);
}

export function UploadImage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function UploadImage200ResponseToJSON(json: any): UploadImage200Response {
    return UploadImage200ResponseToJSONTyped(json, false);
}

export function UploadImage200ResponseToJSONTyped(value?: UploadImage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'url': value['url'],
    };
}

